rm/urls.py
from django.conf.urls import url
from django.shortcuts import render

from . import views

app_name = 'rm'

urlpatterns = [
	url(r'^$', views.index_view, name='index'),

	url(r'^trashes/$', views.trash_list_view, name='trashes'),
	url(r'^trashes/(?P<pk>[0-9]+)/$', views.trash_detail_view, name='trash_detail'),
	url(r'^trashes/create/$', views.trash_create_view, name='trash_create'),
	url(r'^trashes/delete/$', views.trash_delete, name='trash_delete'),
	
	url(r'^operations/$', views.operation_list_view, name='operations'),
	url(r'^operations/(?P<pk>[0-9]+)/$', views.operation_detail_view, name='operation_detail'),
	url(r'^operations/create/$', views.operation_create_view, name='operation_create'),
	url(r'^operations/delete/$', views.operation_delete, name='operation_delete'),
	url(r'^operations/restore/(?P<pk>[0-9]+)/$', views.operation_restore_view, name='operation_restore'),
]

rmsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'', include('rm.urls')),
]

rm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os.path

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone


class Trash(models.Model):
	path = models.CharField(max_length=100)
	maxtime = models.DurationField()

	def __unicode__(self):
		return os.path.basename(self.path.rstrip('/'))


class Operation(models.Model):
	id = models.CharField(max_length=30, primary_key=True)
	name = models.CharField(max_length=100)
	trash = models.ForeignKey(Trash, on_delete=models.CASCADE)
	create_time = models.DateTimeField()

	def __unicode__(self):
		return self.name


class TrashFile(models.Model):
	operation = models.ForeignKey(Operation, on_delete=models.CASCADE)
	old_path = models.CharField(max_length=100)

	def __unicode__(self):
		return os.path.basename(self.old_path.rstrip('/'))

rm/forms.py
from django import forms

from .models import Trash
from .validators import trash_path_validator, operation_path_validator, operation_name_validator


class TrashForm(forms.Form):
	path = forms.CharField(max_length=100, validators=[trash_path_validator,])

	maxtime = forms.BooleanField(required=False)
	maxtime_hours = forms.IntegerField(min_value=0, max_value=999, initial=0)
	maxtime_minutes = forms.IntegerField(min_value=0, max_value=59, initial=0)
	maxtime_seconds = forms.IntegerField(min_value=0, max_value=59, initial=0)


class OperationForm(forms.Form):
	name = forms.CharField(max_length=30, required=False, validators=[operation_name_validator,])
	path = forms.CharField(max_length=100, validators=[operation_path_validator,])
	trash = forms.ModelChoiceField(queryset=Trash.objects.all())
	regex = forms.CharField(max_length=30, required=False)


class OperationRestoreForm(forms.Form):
	politic = forms.ChoiceField(choices=[('safe', 'Safe'), ('agressive', 'Agressive')])

rm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse

from .models import Trash, Operation
from .forms import TrashForm, OperationForm, OperationRestoreForm

from .helpers.trash_helper import create_trash, delete_trash
from .helpers.operation_helper import create_operation, delete_operation, restore_operation, update_operation


def index_view(request):
    return render(request, 'rm/index.html', {})


def trash_list_view(request):
    for operation in Operation.objects.all():
        update_operation(operation)

    return render(request, 'rm/trashes.html', {'trashes': Trash.objects.all()})


def trash_detail_view(request, pk):
    for operation in Operation.objects.all():
        update_operation(operation)

    trash = get_object_or_404(Trash, pk=pk)
    return render(request, 'rm/trash_detail.html', {'trash': trash})


def trash_create_view(request):
    if request.method == 'POST':
        form = TrashForm(request.POST)
        try:
            if form.is_valid():
                create_trash(form=form)
                return HttpResponseRedirect(reverse('rm:trashes'))
            else:
                return render(request, 'rm/error.html', {'message': form.errors})
        except Exception as exc:
            return render(request, 'rm/error.html', {'message': exc.message})
    
    form = TrashForm()
    return render(request, 'rm/trash_create.html', {'form': form})


def trash_delete(request):
    if request.method == 'POST':
        trash = Trash.objects.get(pk=request.POST['pk'])
        delete_trash(trash)
        return HttpResponseRedirect(reverse('rm:trashes'))

    raise Http404()


def operation_list_view(request):
    for operation in Operation.objects.all():
        update_operation(operation)

    return render(request, 'rm/operations.html', {'operations': Operation.objects.all()})


def operation_detail_view(request, pk):
    update_operation(get_object_or_404(Operation, pk=pk))
    operation = get_object_or_404(Operation, pk=pk)
    return render(request, 'rm/operation_detail.html', {'operation': operation})


def operation_create_view(request):
    for operation in Operation.objects.all():
        update_operation(operation)

    if request.method == 'POST':
        form = OperationForm(request.POST)
        try:
            if form.is_valid():
                create_operation(form)
                return HttpResponseRedirect(reverse('rm:operations')) 
            else:
                return render(request, 'rm/error.html', {'message': form.errors})
        except Exception as exc:
            return render(request, 'rm/error.html', {'message': exc.message})

    form = OperationForm()
    return render(request, 'rm/operation_create.html', {'form': form})


def operation_delete(request):
    if request.method == 'POST':
        update_operation(get_object_or_404(Operation, pk=request.POST['pk']))
        delete_operation(get_object_or_404(Operation, pk=request.POST['pk']))
        return HttpResponseRedirect(reverse('rm:operations'))

    raise Http404()


def operation_restore_view(request, pk):
    update_operation(get_object_or_404(Operation, pk=pk))

    if request.method == 'POST':
        form = OperationRestoreForm(request.POST)
        if form.is_valid():
            operation = get_object_or_404(Operation, pk=pk)
            try:
                restore_operation(operation, form)
            except Exception as exc:
                return render(request, 'rm/error.html', {'message': exc.message})
            return HttpResponseRedirect(reverse('rm:operations'))

    operation = get_object_or_404(Operation, pk=pk)
    form = OperationRestoreForm()
    return render(request, 'rm/operation_restore.html', {'form': form, 'operation': operation})

rm/templates/rm/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %}{% endblock %}</title>

		<link href="{% static 'rm/css/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'rm/css/font-awesome.css' %}" rel="stylesheet">
		<link type="text/css" href="{% static 'rm/css/style.css' %}" rel="stylesheet">
	</head>
  
	<body background="FF69B4">
		<div class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="{% url 'rm:trashes' %}">
						<i class="fa fa-trash"></i>
						Trashes
					</a>
					<a class="navbar-brand" href="{% url 'rm:operations' %}">
						<i class="fa fa-edit"></i>
						Operations
					</a>
				</div>
			</div>
		</div>
		<div style="background-color: rgba(0, 255, 255, .3);">
			<hr>
			<h1 align="center">{% block header%}{% endblock%}</h1>
			<hr>
		</div>
		{% block content %}{% endblock %}

	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	    <script src="{% static 'rm/js/bootstrap.js' %}"></script>
	</body>
</html>

rm/templates/rm/error.html
{% extends "rm/base.html" %}

{% block title %}Error{% endblock %}

{% block header%}Error{% endblock %}

{% block content %}
	<div class="container">
		{{ message }}
	</div>
{% endblock %}

rm/templates/rm/index.html
{% extends "rm/base.html" %}

{% block title %}RMSite{% endblock %}

{% block header%}RMSite{% endblock %}

{% block content %}

{% endblock %}

rm/templates/rm/operation_create.html
{% extends "rm/base.html" %}

{% block title %}Create operation{% endblock %}

{% block header%}Create operation{% endblock %}

{% block content %}
	<div class="container">
		<form role="form" action="{% url 'rm:operation_create' %}" method="post">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">
					<i class="fa fa-check"></i>
					Create
				</button>
			</div>
		</form>

		<form action="{% url 'rm:trashes' %}">
			<button class="btn btn-default" type="submit">
				<i class="fa fa-undo"></i>
				Back
			</button>
		</form>
	</div>
{% endblock %}

rm/templates/rm/operation_detail.html
{% extends "rm/base.html" %}

{% block title %}Operation {{ operation }}{% endblock %}

{% block header%}{{ operation }}{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operation_restore' operation.pk %}">
						<button class="btn btn-success" type="submit">
							<i class="fa fa-share-square-o"></i>
							Restore
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operation_delete' %}" method="post">
						{% csrf_token %}
						<button name="pk" value="{{ operation.pk }}" class="btn btn-danger" type="submit">
							<i class="fa fa-remove"></i>
							Delete
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operations' %}">
						<button class="btn btn-default" type="submit">
							<i class="fa fa-arrow-left"></i>
							Back
						</button>
					</form>
				</div>
			</div>
		</div>
		<table class="table table-hover table-condensed" align="center">
			<tr>
				<th>Files</th>
				<th>Old path</th>
			</tr>
			{% for file in operation.trashfile_set.all %}
				<tr>
					<td>{{ file }}</td>
					<td>{{ file.old_path }}</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

rm/templates/rm/operation_restore.html
{% extends "rm/base.html" %}

{% block title %}Restore operation{% endblock %}

{% block header%}Restore {{operation}}{% endblock %}

{% block content %}
	<div class="container">
		<form role="form" action="{% url 'rm:operation_restore' operation.pk %}" method="post">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">
					<i class="fa fa-check"></i>
					Restore
				</button>
			</div>
		</form>
	</div>
{% endblock %}

rm/templates/rm/operations.html
{% extends "rm/base.html" %}

{% block title %}Operations{% endblock %}

{% block header%}Operations{% endblock %}

{% block content %}
	<div class="container">
		<div class="form-group" align="left">
			<form action="{% url 'rm:operation_create' %}" method="get">
				<button class="btn btn-success" type="submit">
					<i class="fa fa-plus-circle"></i>
					New operation
				</button>
			</form>
		</div>
		<table class="table table-hover table-condensed" align="center">
			<tr>
				<th>Name</th>
				<th>Trash</th>
				<th>Create time</th>
			</tr>
			{% for operation in operations %}
				<tr>
					<td><a href="{% url 'rm:operation_detail' operation.pk %}">{{ operation }}</a></td>
					<td><a href="{% url 'rm:trash_detail' operation.trash.pk %}">{{ operation.trash }}</a></td>
					<td>{{ operation.create_time }}</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

rm/templates/rm/trash_create.html
{% extends "rm/base.html" %}

{% block title %}Create trash{% endblock %}

{% block header%}Create new trash{% endblock %}

{% block content %}
	<div class="container">
		<form role="form" action="{% url 'rm:trash_create' %}" method="post">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">
					<i class="fa fa-check"></i>
					Create
				</button>
			</div>
		</form>
		<form action="{% url 'rm:trashes' %}">
			<button class="btn btn-default" type="submit">
				<i class="fa fa-arrow-left"></i>
				Back
			</button>
		</form>
	</div>
{% endblock %}

rm/templates/rm/trash_detail.html
{% extends "rm/base.html" %}

{% block title %}Trash {{ trash }}{% endblock %}

{% block header%}{{ trash.path }}{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:trash_delete' %}" method="post">
						{% csrf_token %}
						<button name="pk" value={{ trash.pk }} class="btn btn-danger" type="submit">
							<i class="fa fa-remove"></i>
							Delete
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:trashes' %}">
						<button class="btn btn-default" type="submit">
							<i class="fa fa-arrow-left"></i>
							Back
						</button>
					</form>
				</div>
			</div>
		</div>
		<div class="tabs">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#tab-1" data-toggle="tab">Operations</a></li>
				<li><a href="#tab-2" data-toggle="tab">Files</a></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab-1">
					<table class="table table-hover table-condensed" align="center">
						{% for operation in trash.operation_set.all %}
							<tr>
								<td><a href="{% url 'rm:operation_detail' operation.pk %}">{{ operation.name }}</a></td>
							</tr>
						{% endfor %}
					</table>
				</div> 
				<div class="tab-pane fade" id="tab-2">
					<table class="table table-hover table-condensed" align="center">
						<tr>
							<th>Name</th>
							<th>Old path</th>
						</tr>
						{% for operation in trash.operation_set.all %}
							{% for file in operation.trashfile_set.all %}
								<tr>
									<td>{{ file }}</td>
									<td>{{ file.old_path }}</td>
								</tr>
							{% endfor %}
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

rm/templates/rm/trashes.html
{% extends "rm/base.html" %}

{% block title %}Trashes{% endblock %}

{% block header%}Trashes{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:trash_create' %}">
						<button class="btn btn-success" type="submit">
							<i class="fa fa-plus-circle"></i>
							New trash
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operation_create' %}">
						<button class="btn btn-success" type="submit">
							<i class="fa fa-plus-circle"></i>
							New operation
						</button>
					</form>
				</div>
			</div>
		</div>
		<table class="table table-hover table-condensed" align="center">
			<tr>
				<th>Path</th>
				<th>Maxtime</th>
				<th>Remove</th>
			</tr>
			{% for trash in trashes %}
				<tr>
					<td><a href="{% url 'rm:trash_detail' trash.pk %}">{{ trash }}</a></td>
					<td>{{ trash.maxtime }}</td>
					<td>
						<form action="{% url 'rm:trash_delete' %}" method="post">
							{% csrf_token %}
							<button class="btn btn-link" name="pk" value={{ trash.pk }} type="submit">
								<i class="fa fa-remove"></i>
							</button>
						</form>
					</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}